import "./globals.css";
import { Inter } from "next/font/google";
import { Open_Sans } from "next/font/google";
import { Nanum_Gothic } from "next/font/google";
import styles from "./layout.module.css";
import Link from "next/link";

const sans = Open_Sans({ subsets: ["latin"] });
// 나눔고딕은 variable font 가 아니기에 옵션 지정 필요
const gothic = Nanum_Gothic({
  weight: "700",
  subsets: ["latin"],
});

export const metadata = {
  title: "멋진 제품 사이트",
  description: "Generated by 멋진닷컴",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={sans.className}>
        <header className={styles.header}>
          <h1 className={gothic.className}>Demo Note</h1>
          <nav className={styles.nav}>
            <Link href="/products">Products</Link>
            <Link href="/contact">Contact</Link>
            <Link href="/about">About</Link>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
